[fonts]
size = 17

[fonts.regular]
family = "MonofurZenMaruGothic"
style = "regular"

[fonts.bold]
family = "MonofurZenMaruGothic"
style = "regular"

[fonts.italic]
family = "MonofurZenMaruGothic"
style = "regular"

[fonts.bold-italic]
family = "MonofurZenMaruGothic"
style = "regular"

[cursor]
shape = "block"
blinking = false

[section]
copy-on-select = true
confirm-before-quit = true

[editor]
theme = "atom"
program = "nvim"
args = []

[platform]
windows.shell = { program = "nu" }

[window]
opacity = 0.75

[renderer]
backend = "Webgpu"

[navigation]
mode = "Tab"
