local opt = vim.opt

opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.clipboard = "unnamed"
opt.number = true
opt.relativenumber = true
opt.hlsearch = true
opt.smartindent = true
opt.laststatus = 3
opt.wildmenu = true
opt.ruler = true
opt.history = 9999
opt.encoding = "utf8"
opt.termguicolors = true
opt.signcolumn = "yes"
opt.updatetime = 100
opt.scrolloff = 8
opt.wrap = false
opt.splitright = true
opt.splitbelow = true
opt.foldlevel = 99
opt.foldlevelstart = 99
opt.foldenable = true
opt.guicursor = "i-ci:hor25"
